### PR TITLE
Added Ctrl+0 to remove flags

### PR DESCRIPTION
**Pull request by lindenr**

### CODE REVIEW

**Comment by dae** [comment]
I'm not sure this is really required - are you aware you can use ctrl+1 to turn off the red tag, or press it again to turn off any other tag?

**Comment by lindenr** [comment]
Yes. However (as well as being a natural thing to expect ctrl+0 to do) removing a flag is a single operation from the user's perspective - no one's first thought to remove a green flag is by e.g. cycling through red, unless anki has taught them this behavior. So imo anki should allow the user to do what they intend directly rather than jumping through hoops.

**Comment by dae** [comment]
Thanks for the feedback, I'll keep an eye on requests for this. If it does get introduced in the future, it will need to be added to the browser and the popup menu as well so it is discoverable.

**Comment by dae** [comment]
The number of flags available doesn't matter with the ctrl+1 x 2 approach I mentioned above - have you actually tried using it for a while? It also has the advantage that it can be done more easily with one hand.

**Comment by lindenr** [comment]
Hi! Yeah I have, but I preferred this. For a while I had the ctrl+0 change in my local anki and used it quite often. I definitely felt some benefit from having it be a single action that doesn't depend on the color of the flag, but it's obviously subjective.

**Comment by dae** [comment]
I'd like to see a bit more demand for this before considering it I'm afraid.

**Pull request closed without merging**
