### PR TITLE
pass factor into function through parameter

### PR DESCRIPTION
**Pull request by ankitest**
Let addons' authors to set up their own factor values on forget and resched cards.

### CODE REVIEW

**Comment by dae** [comment]
A better way to do this would be to define the starting factor in consts.py and then use that constant in both sched.py and the other places it's used.

**Comment by ankitest** [comment]
One is not in another's road.

**Comment by dae** [comment]
I'd prefer to fix it properly :-) I'll leave this around as a reminder.

**Comment by dae** [comment]
Done in https://github.com/dae/anki/commit/227ca090db546363dbda6949ec18ef467d67eed7

**Pull request closed without merging**
