### PR TITLE
Don't use os.chdir, and create setup.py for "ankilib" usage

### PR DESCRIPTION
**Pull request by jkitching**

### CODE REVIEW

**Comment by dae** [comment]
Thank you for the contribution. I'll be happy to accept the media changes if you could do the following:

- send us a private message as mentioned in the LICENSE file
- split the media changes from the setup.py change, as I'm not keen on including a setup.py
- ensure the changes don't break the unit tests

**Comment by dae** [comment]
Please create a new pull request if you'd like to do so.

**Comment by dae** [comment]
Actually, another issue with merging this is it's likely to break things for users with long filenames, as using the absolute path will cause Anki to hit up against the MAX_PATH limit sooner - we will need to fix that issue prior to making this change.

**Comment by jkitching** [comment]
In what situations are problems with MAX_PATH being encountered?  On Windows?  Linux?  Is there an existing bug of people complaining of hitting the limit?

If it's Windows, seems like the correct solution is to prefix absolute paths with "\\?\".

**Comment by dae** [comment]
There have been a number of cases where users added a file on a non-Windows machine, and then syncing broke on Windows because the file name was too long. \? should do what we want, but we'll need to make sure we're not passing any byte strings to calls that use it.

**Comment by jkitching** [comment]
This probably deserves to be discussed in a separate bug... but I can't see any "bugs" section of Github.  Seems like there needs to be a "project" for that to happen, and I'm not sure if that costs money?

Regardless, regarding the Windows long file name issue:

I've done some experimenting on a Windows machine.  It turns out that using relative paths is a moot point.  Regardless of how short or long the relative path is -- the limiting factor is the expanded/absolute path.

Example:

```python
os.chdir('C:\\test')
open('_' * 251, 'w').close()  # succeeds
open('_' * 252, 'w').close()  # fails
open(('D' * 100) + '\\' + ('_' * 150), 'w').close()  # succeeds
open(('D' * 100) + '\\' + ('_' * 151), 'w').close()  # fails
os.mkdir('D' * 100)
os.chdir('D' * 100)
open('_' * 150, 'w').close()  # succeeds
open('_' * 151, 'w').close()  # fails
```

So, merging the above patch should not affect (make worse) the MAX_PATH situation on Windows.

I'll take another look at the licensing stuff and resubmit a new pull request.

**Comment by dae** [comment]
Thanks, that'd be great. Interesting that relative paths don't help - I'd read something to the contrary in the past. Should have actually tested it!

**Pull request closed without merging**
