### PR TITLE
Increment cloze number correctly after removing cloze deletions

### PR DESCRIPTION
**Pull request by dlon**
Undoing/deleting a cloze deletion and quickly creating a new one increments the number incorrectly. Waiting for the key cmd before creating the cloze fixes this.

### CODE REVIEW

**Comment by dae** [comment]
Perhaps a cleaner way to do this would be to have the cloze function call saveNow() to run the cloze deletion after the current field data had been saved?

**Comment by dae** [comment]
Thanks for that, and sorry for the delay - will look into this and get back to you in a few days.

**Comment by dae** [comment]
I've applied a slightly modified version - please let me know if it doesn't work for you: https://github.com/dae/anki/commit/46a540e22f50101e88b56af1f701176e788ca217

**Comment by dlon** [comment]
That works. Thanks.

**Pull request closed without merging**
