### PR TITLE
"@" suspends cards with text input for some keyboard layouts

### PR DESCRIPTION
**Pull request by dlon**
Even if the type answer box is in focus. The issue occurs with a Swedish keyboard layout (where Alt Gr-2 is the combination for @) but works as expected with an English layout.

My workaround is to ignore some key events when the input element has focus.

Qt version 5.11.1. Possibly a related issue: https://bugreports.qt.io/browse/QTBUG-53006

### CODE REVIEW

**Comment by dae** [comment]
I filed a report about this a while back: https://bugreports.qt.io/browse/QTBUG-73247

The issue exists in the Browse screen as well. A workaround that doesn't involve retaining state on the Python side would be ideal, as that feels fragile, and may fail if the web channel events are delayed. I wonder if the keys could be swallowed in Javascript instead?

**Comment by dae** [comment]
Thanks dlon, let's give this a go - hopefully Qt will address the issue properly in the future. I'll need to make a tweak so it handles contenteditable divs.

**Comment by dae** [comment]
Just curious - why the exception for numbers?

**Comment by dlon** [comment]
Just so that ctrl-1 and up work

Den ons 10 apr. 2019 08:16Damien Elmes <notifications@github.com> skrev:

**Pull request merged**
