### PR TITLE
Allow to run App&GUI without entering the main event loop

### PR DESCRIPTION
**Pull request by krassowski**
Hello, I want to ask for merging this small change for runanki script.

**Why?**
I want to write advanced unit & integration tests for my add-on; it would require the Anki app to be initialized and ready for work. I do not want to hardcode the definition of the `run()` function as I believe it may be subject to various improvements in the future. 

**Is it really worth merging?**
I read the contributing guidelines and I am aware that changes which would be beneficial only for add-ons are discouraged in the 2.1.x cycle. Still, I deem the change (and the tests which come with it) highly beneficial for all the Anki ecosystem:
1. The new test reassures that the app will start (!)
2. The test runs full initialization process which will highlight potential regressions (e.g. starting a new thread and not cleaning it up in `mw.cleanupAndExit()` or adding new global variables - like `hooks._hooks` - which are persistent between tests)
3. Better tested add-ons means less support tickets to deal with and more happy users :)

**Contributing guidelines checkup**
- [ ] Primarily Bugfixes
- [x] Maintaining Style
- [x] Tests Must Pass
- [x] Do One Thing
- [x] License

Edit: All the tests pass again.
I have split the PR into two: this one (without additional tests) and #212 (which includes additional tests). Please choose which one suits your preferences best and reject the other one.

### CODE REVIEW

**Comment by krassowski** [comment]
The failing build on Travis seems to indicate lack of `sip` dependency in `requirements.txt` file.

**Comment by dae** [comment]
Qt will likely not be able to start without a display to draw on to. I think it's better that the unit tests remain able to run in a text environment, so any GUI tests should be implemented separately - perhaps in your add-on's repo for now. I'm ok with your changes to aqt/__init__.py to make this easier to do - could you update the request to limit the changes to that? A comment at the top of _run() explaining why it allows for arguments would be good too :-)

**Comment by krassowski** [comment]
Thanks! I will add the requested comment. 

> Qt will likely not be able to start without a display to draw on to.

It will! I mean, I did it before (even with mahplotlib and so on) in there: https://github.com/kn-bibs/dotplot. It is even possible to add a fake display for GUI. It just seems that there is some packaging/compilation issue (or something like that) on Travis.

I will do a few checks and let you know what exactly causes Travis to fail. I consider having as many tests running on Travis as possible beneficial but I understand that GUI testing may be cumbersome and the tests may not go well on other platforms (I do not have a Mac to test on it).

> I'm ok with your changes to aqt/init.py to make this easier to do - could you update the request to limit the changes to that?

Ok, If I do not manage to fix the tests too until the end of the day (or I fix it and you still prefer not to add those) I remove other changes ;)

Thank you again.

**Comment by krassowski** [comment]
@dae I got it - all tests pass correctly on Travis now! I did the checkup on a separate branch of my fork - here is [the extensive build log](https://travis-ci.org/krassowski/anki/builds/278212074) and here is [the comparison against the master branch](https://github.com/dae/anki/compare/master...krassowski:travis).

What is your decision now, should I add here the code which makes the additional, GUI tests build on Travis or should I remove the new tests completely?

**Comment by dae** [comment]
Sorry it's taken me so long to get back to you. I think it's best to keep the tests/ folder focused on libanki, as it keeps things simple and makes things easier for other clients that want to port the tests. If there's demand for a GUI testing framework, a separate folder for the GUI tests would be an option moving forward.

**Comment by krassowski** [comment]
Thank you. I understand your decision - the separate folder for GUI (or `aqt` really) sounds like a good idea. If you were to implement GUI testing sometime in the future, feel free to reuse my code from the other branch. Thank you again.

**Pull request merged**
