### PR TITLE
Manage dependencies with pipenv.

### PR DESCRIPTION
**Pull request by HaoZeke**
This is a more distro agnostic method..

### CODE REVIEW

**Comment by dae** [comment]
Thank you for the contribution; I will leave it around to look into in the future.

**Comment by patcon** [comment]
If we add pipenv support, I would then love to discuss adding a setup.py like this, so that we can use this desktop code as a library (and use all the great pre-written functionality here in scripts).

**Comment by dae** [comment]
No special installation is required, just start your script with PYTHONPATH set to the Anki source folder then import the anki module.

**Comment by dae** [comment]
Revisiting the original issue, pipenv seems to have a bit of a mixed reputation at the moment, and I'd prefer to keep sip&PyQt out of the base requirements to make it easy for users to compile their own PyQt or use their Linux distro's version - so I'm afraid it's a no for now.

**Pull request closed without merging**
