### PR TITLE
Support snap packaging from Ubuntu

### PR DESCRIPTION
**Pull request by woodrow-shen**
This commit introduces the packaging as snap developed by
Canonical/Ubuntu and it makes anki snap more easy to spread around the
world and then any distribution can get the anki through snapd.
In order to package snap, snapcraft.yaml is used for building anki snap
from scratch. However, the python plugin from snapcraft needs to support
setuptools, so that's why setup.py is created although it's created by
manual and tricky way. First Anki snap will be based on latest LTS version
of Ubuntu, which is actually called Core 18.

### CODE REVIEW

**Comment by woodrow-shen** [comment]
@dae , I'd like to appreciate your hard work to let me get a great benefit from Anki itself, while I'm also a user for Linux/Mac/iOS version. It does very well for convenience to synchronize anywhere. As Anki deb was not updated anymore (Please rectify me If I'm wrong), I was thinking if snap can be introduced. Therefore the purpose what I'm eager to do is trying to package Anki as snap for maintenance option.
Hopefully we can have more discussions about this if you're interested, thanks.
There are few references can be useful:

[1] Snap overall, https://docs.snapcraft.io/snapcraft-overview/8940
[2] Snapcraft, the tool to create a snap (https://docs.snapcraft.io/snap-documentation/3781)
[3] Ubuntu Core, the specific OS suitable for IoT, (https://www.ubuntu.com/core)

**Comment by dae** [comment]
Hi Shen,

I'm not quite ready to support snaps officially, as not all distros support them, and I imagine this snap will not run on older Ubuntu installations either. I appreciate you taking the time to contribute however, and I'll leave this pull request open to revisit in the future.

**Comment by woodrow-shen** [comment]
@dae , 
Thanks your replying quickly, and you're right for outdated Ubuntu and snapd needs certain security updates for kernel. Keeping PR is fine to me, and I'd like to publish my personal snap (The snap name is NOT *Anki* but *anki-woodrow*) based on GPLv3 on store but it shouldn't influence upstream. Meanwhile, the "Snap Store" preserves "Anki" name for some reason, and I think it's for community.

**Comment by dae** [comment]
That's no problem. To limit the number of extra support requests this generates, it would be great if you could make it clear to potential users that it's an unofficial package, and could build the snaps based on stable releases rather than git head.

**Comment by woodrow-shen** [comment]
The anki snap can be installed by using the following command (if you already installed snapd):

`snap install anki-woodrow --edge --devmode`

There is still a problem for audio part, and will figure out.:)

**Comment by woodrow-shen** [comment]
The audio part is just fixed, so now Anki snap can be installed by using the following command (if you already installed snapd):

snap install anki-woodrow --edge

**Comment by SamMorrowDrums** [comment]
Thanks for doing this! Seems to work well - I noticed some logs to the console, but as far as I can tell everything was working as it should. I logged in and sync'd - didn't work on cards yet.

```
qt: Qt: Session management error: None of the authentication protocols specified are supported
qt: QApplication: invalid style override passed, ignoring it.
qt: Installed Qt WebEngine locales directory not found at location /usr/share/qt5/translations/qtwebengine_locales. Trying application directory...
qt: Qt WebEngine resources not found at /usr/share/qt5/resources. Trying parent directory...
qt: Qt WebEngine resources not found at /usr/share/qt5. Trying application directory...
[8361:8361:0507/102528.528007:FATAL:credentials.cc(295)] Check failed: 0 == sys_unshare(CLONE_NEWUSER). : Operation not permitted

...

Installed Qt WebEngine locales directory not found at location /usr/share/qt5/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at /usr/share/qt5/resources. Trying parent directory...
Qt WebEngine resources not found at /usr/share/qt5. Trying application directory...
```

On a probably unrelated note:

I Have a 4k monitor, and laptop screen (run always with 2x scaling), and interestingly the mouse shows up small, and the font-size switches between monitors, so on the external monitor it's a little small, and on the laptop monitor it is quite large text.

I was surprised that there was a change, I'm not sure how DPI / screen size / OS scaling work with Anki and with Snap, but mentioned in case there was something more to it.

Most likely you an ignore this for now! Just wanted to report back on a successful install

Dell XPS 9380 - running ElementaryOS (Ubuntu 18.04LTS base) - latest kernel.

**Comment by podcherklife** [comment]
Not sure if this is a good place to place this comment, but snap package does not work for me on Ubuntu 19.04 unless I run it with DISABLE_WAYLAND=1 variable.

package version is `2.1.14+master-commit.dce0428` 

This is what i get 
```
$ anki-woodrow.anki 
qt: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by woodrow-shen** [comment]
> Not sure if this is a good place to place this comment, but snap package does not work for me on Ubuntu 19.04 unless I run it with DISABLE_WAYLAND=1 variable.
> 
> package version is `2.1.14+master-commit.dce0428`
> 
> This is what i get
> 
> ```
> $ anki-woodrow.anki 
> qt: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
> in "".
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Reinstalling the application may fix this problem.
> Aborted (core dumped)
> ```

**Comment by woodrow-shen** [comment]
> Not sure if this is a good place to place this comment, but snap package does not work for me on Ubuntu 19.04 unless I run it with DISABLE_WAYLAND=1 variable.
> 
> package version is `2.1.14+master-commit.dce0428`
> 
> This is what i get
> 
> ```
> $ anki-woodrow.anki 
> qt: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
> in "".
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Reinstalling the application may fix this problem.
> Aborted (core dumped)
> ```

@podcherklife I'd like to reproduce this issue next week as I still develop & test on 18.04.

**Comment by woodrow-shen** [comment]
> > Not sure if this is a good place to place this comment, but snap package does not work for me on Ubuntu 19.04 unless I run it with DISABLE_WAYLAND=1 variable.
> > package version is `2.1.14+master-commit.dce0428`
> > This is what i get
> > ```
> > $ anki-woodrow.anki 
> > qt: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
> > in "".
> > 
> > Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> > 
> > Reinstalling the application may fix this problem.
> > Aborted (core dumped)
> > ```
> 
> @podcherklife I'd like to reproduce this issue next week as I still develop & test on 18.04.

@podcherklife I didn't get the same error but I just found that the similar topic from our forum:
https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055

Exactly, using DISABLE_WAYLAND=1 is one of options to work, and I think the solution can be included in next version.

Thanks to bring this problem about wayland.

**Comment by lyveng** [comment]
> Not sure if this is a good place to place this comment, but snap package does not work for me on Ubuntu 19.04 unless I run it with DISABLE_WAYLAND=1 variable.
> 
> package version is `2.1.14+master-commit.dce0428`
> 
> This is what i get
> 
> ```
> $ anki-woodrow.anki 
> qt: This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
> in "".
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Reinstalling the application may fix this problem.
> Aborted (core dumped)
> ```

The same issue happens on debian buster as well and the workaround of using DISABLE_WAYLAND=1 works.

**Comment by dae** [comment]
Closing this for now, but I'll keep an eye on snap support moving forward.

**Comment by adrian5** [comment]
I noticed this snap tries to open dotfiles in $HOME — Any idea why? AppArmor intervened, but others snaps I use don't seem to do that.

**Comment by YamashitaRen** [comment]
Hello, anki snap is currently missing some cursor themes :
```
$ ls /snap/keepassxc/784/usr/share/icons
Adwaita  default  DMZ-Black  DMZ-White  hicolor  Humanity  Humanity-Dark  LoginIcons  ubuntu-mono-dark  ubuntu-mono-light
```
Available themes :
```
$ ls /snap/gtk-common-themes/current/share/icons/
Adwaita         communitheme  elementary-xfce          hicolor        Papirus-Adapta-Maia        Papirus-Maia      ubuntu-mono-light
Ambiant-MATE    DMZ-Black     elementary-xfce-dark     HighContrast   Papirus-Adapta-Nokto-Maia  Radiant-MATE      Yaru
breeze_cursors  DMZ-White     elementary-xfce-darker   Humanity       Papirus-Dark-Maia          Suru
Breeze_Snow     elementary    elementary-xfce-darkest  Humanity-Dark  Papirus-Light-Maia         ubuntu-mono-dark
```
It is notably missing Breeze.

**Pull request closed without merging**
