### PR TITLE
Save|Restore Geom in getText

### PR DESCRIPTION
**Pull request by ankitest**
in fact for Add Tags | Remove Tags
minWidth= param also

### CODE REVIEW

**Comment by dae** [comment]
getText() is a helper function used in various places, and it's potentially confusing for it to be remembering the size, as users may not realise that changing it in one location changes it in another - I think it's better as is, sorry.

**Comment by ankitest** [comment]
I find `getText()` only in `models.py`  `preferences.py`  `utils.py`  `BeautifulSoup.py`

`BeautifulSoup.py` uses own def getText()

`models.py`  uses this one only to add and rename note types

`preferences.py` only to setup and confirm password on profile

not so various. but well

**Comment by dae** [comment]
You are forgetting about all the add-ons out there that use getText() or getOnlyText(). The helpers should not specify their own geomKey, they should receive it from the calling code (eg the code in the browser that calls them)

**Comment by ankitest** [comment]
getOnlyText, yes

**Pull request closed without merging**
