### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by andihafner**
line 33 'harbour' instead of 'harbor'

### CODE REVIEW

**Comment by dae** [comment]
thanks :-)

**Comment by julienbaley** [comment]
Just US vs ROTW spelling...

**Comment by dae** [comment]
It was a typo; andi just accidentally spelt it correctly in the pull request :-)

**Comment by andihafner** [comment]
@julienbaley 

Basicliy you're right, my fault was FIXING 'habour' to 'harbour' (which is right) while COMMENTING "'harbour' instead of 'harbor'", which indeed is nonsense. One could say: "Fixing a typo with another typo..."

You'd be sorry about that (Unfortunately, my native language is German...)

**Pull request merged**
