### PR TITLE
Enable anki reviewer to compare multiple type: fields on one card

### PR DESCRIPTION
**Pull request by Ongy**
I created a small patch to allow multiple independent `type:` fields on the same card.

This is especially useful to study something like chinese or japanese.

Example screenshot:

### CODE REVIEW

**Comment by corpulentcoffee** [comment]
I really want this too. I have some cards for practicing lookalike/soundalike words, so I [hacked something similar into my desktop Anki](https://github.com/corpulentcoffee/anki/commit/cefa6a5fbf9339d2d0e02efa089b0267317bbf58) for it, but my solution was not fully-baked.

If Damien is interested in this (and he might not be, since it would be a major change for a point release and also because it sort of violates the "one piece of information per card" philosophy), there are some other things to consider...

- AnkiDroid only supports one `type:` field right now [don't know about AnkiMobile on iOS], so maybe that project should/would want to update too
- it would be nice if the card layout screen (`clayout` module) used the same markup for the input text field (i.e. with `name=typetxt`) so that if someone uses a CSS selector that uses this (e.g. `input[name=typetxt]`) that their styles show up correctly there

**Comment by Ongy** [comment]
"One piece of information per card" is pretty hard to hold for the Kanji usecase, since they have at least 3 parts of information that should be associated.
Anki allows a variable amount of fields on each card aswell. I don't really see a reason why it shouldn't be allowed for `type:` fields.

 * I haven't looked to much into AnkiDroid source, but I think it wont be easy to update the UI for multiple inputs there. I don't have any Idea about IOS.
 * I can fix issues related to the desktop version without problems, I mainly wanted to get some feedback for the current state of the patch, since I don't know any web technologies (html/js).

**Comment by corpulentcoffee** [comment]
For what it's worth, I used your patch earlier today with my cards that have multiple `type:` fields and it worked for my basic use case. :+1: 

I haven't tested some of the other things it touches, though (like cloze and detecting empty cards).

**Comment by dae** [comment]
While it does sort of violate the minimum information principle, we already allow that by allowing multiple fields to be shown at once as Ongy pointed out. A bigger issue is how multiple input boxes would be handled on small mobile devices, as there are issues such as webkit not allowing embedded text boxes to bring up the keyboard without user intervention IIRC. I'll have another look into that at some point, but for now I'd prefer not to include this in a point release, though I'm sure people would be appreciative if you could release it as an add-on.

**Comment by Ongy** [comment]
I uploaded this as an addon.
I made 2 additions there:
 * The addon also adds the `name='typetext'` in clayout.
 * Esc removes focus on any input field


Link: https://ankiweb.net/shared/info/689574440?ok=1

**Comment by dae** [comment]
Thanks!

**Pull request closed without merging**
