### PR TITLE
change new card queuing order to random instead of due for new cards

### PR DESCRIPTION
**Pull request by TylerNakamura**
trying to make it possible to select a random new card instead of the next due one. Thoughts?

### CODE REVIEW

**Comment by ankitest** [comment]
What should I do if I still want to select a new card in a next due order?

**Comment by dae** [comment]
Sorry, there are multiple issues with your patch. It doesn't allow users to randomise certain cards while keep others in a specific order, provides no reproducibility in the case of undo/edits/etc, and prevents Anki from using an index to do the lookup which results in significantly slower query times on large collections.

**Comment by TylerNakamura** [comment]
Here was my motivation:

I currently have around 10 decks, all under a parent deck. My goal is to be able to study all the child decks, by just clicking "study" on the parent deck. This functionality works, however, it seems to pull cards from child deck 1, then child deck 2, and so forth. Each child deck is rather large and I was hoping to study each of the child decks so that I could study each incrementally and concurrently.

I was hoping to make it behave, so that it might (on average) pull one card from each child deck in a given study session.

How can I accomplish this?

Thanks for taking the time to look at the request, it is greatly appreciated. Anki is awesome software.

**Comment by ankitest** [comment]
*Deck 1* Options - pop-up menu under gear right after *Options group:* - 
Add - **1 new 1 review per day** - OK  
New Cards *tab* - New cards/day - **1** 
Reviews *tab* - Maximum reviews/day - **1** - OK  
*Deck 2* Options - pop-up menu under gear right after *Options group:* - 
click on drop-down list - select *1 new 1 review per day* - OK

**Comment by TylerNakamura** [comment]
Not sure why I didn't think of that. Thanks guys, keep up the awesome work. I try to promote Anki whenever I can :smiley:

**Comment by dae** [comment]
ankitest: thanks!

Tyler: thanks for your support!

**Pull request closed without merging**
