### PR TITLE
next interval >= prev interval + 1

### PR DESCRIPTION
**Pull request by ankitest**
http://ankisrs.net/docs/manual.html#reviews

One final thing to note is that Anki forces a new interval to be at least 1 day longer than it was previously so that you don’t get stuck reviewing with the same interval forever. 

https://anki.tenderapp.com/discussions/ankidesktop/18382-new-interval-does-not-seem-to-be-updated-with-ease-at-130-and-current-interval-at-7-days

In some cases interval does not grow in fact.

### CODE REVIEW

**Comment by julienbaley** [comment]
Well, this means that Anki wouldn't respect the max interval the user has set.

**Comment by ankitest** [comment]
It happens not so seldom.  
I execute `SELECT count(*) FROM revlog where lastIvl = ivl and ivl>0`  
and recieve 739.

**Comment by julienbaley** [comment]
Your test doesn't mean much without the size of the collection and knowledge of your settings, the query returns 13800 for me (out of 36000), simply because a lot of my cards have reached the maximal interval I've set.

Since this is a problem with the fuzzy interval, why not try to fix it? Your change still means that you're going to be more or less stuck for a while, doing 7-8-9-10, when really, answering Good should get you past that stage. The scaling factors could be improved, perhaps?

Oh, and perhaps a good time to clean _adjRevIvl(self, card, idealIvl) which takes "card" for nothing?

**Comment by ankitest** [comment]
[Last formula](https://github.com/dae/anki/pull/131/commits/181c6f6f91ef130d81017bc8eae38764cc248b58) works as manual describes, isn't it?

I agree, that answer Good should enlarge small factor till it does not reach 250%,  
but that is totally separate problem from this one, IMHO.

**Comment by julienbaley** [comment]
Strictly speaking, yes, and I think it's fine. From a code perspective, I'd say put a new line after the second comma so that it stays under 79 chars (PEP8).

Not sure this is the PR to do so, but the goal of fuzzy interval is to "smooth out occasional peaks in due card counts", which is apparently not what Anki does for smaller intervals as it tends to accumulate cards in the 7 day regions (thereby aggravating the problem), even if you force increase by 1 (it's still lagging).

**Comment by ankitest** [comment]
Thanks for PEP8 hint.

**Comment by dae** [comment]
This and the other pull request look reasonable, thanks. I'm in the middle of some changes at the moment, and will return to apply these once they're done.

**Pull request merged**
