### PR TITLE
Simplify installing add-ons from local files

### PR DESCRIPTION
**Pull request by glutanimate**
Introduces the ability to conveniently install add-ons from local add-on archives, doing away with a lot of the common pitfalls when distributing add-ons outside of AnkiWeb.

### Background

Installing add-ons from AnkiWeb is as easy at it can be. However, some scenarios like running beta tests, sharing private builds, or distributing extensions to existing add-ons still require users to install add-ons manually. This process is fraught with pitfalls such as users downloading the wrong archive, unpacking it incorrectly, or moving the add-on files to the wrong location. This PR seeks to address these issues by introducing a new file type for distributing Anki add-ons and extending the add-on UI with a number of convenience features for handling these files.

#### Overview

APKX files are just a ZIP archive of the add-on with a manifest file contained within. The manifest follows JSON notation and allows add-on authors to define properties such as the add-on's name, modification date, and the destination package the add-on should be unpacked to.

In its current implementation the manifest file recognizes the following keys:

- `name` (`str`) [required]: Display name of the add-on (e.g. `Review Heatmap`)
- `package` (`str`) [required]: Package name of the add-on, i.e. the subfolder within Anki's `addons21` folder the archive should be unpacked to (e.g. `review_heatmap` or `1771074083`)
- `mod` (`int`) [optional]: Modification/creation time of the package as a unix timestamp (similar to AnkiWeb and in lieu of a canonical versioning scheme)

This schema could be easily extended in the future if the need arises.

#### Reasoning

*Why the need for a manifest?*

Without a manifest we are stuck with using file names to determine the add-on's metadata, which – as you might imagine – is not a great option.

Manifests seem to be the industry standard for similar extension systems, e.g. Chrome extensions, Firefox plugins, and VS Code extensions.

*Why not use the existing meta.json file for supplying metadata?*

`meta.json` primarily keeps track of add-on installation and configuration state. Mixing in static package metadata didn't seem like a good idea.

*Why use a custom file format rather than ZIP files?*

I explored using ZIP files in an initial, unpublished version of this PR, but quickly arrived at the conclusion that this would be a misstep. My main concern with ZIP files is that users will not be able to easily identify what does and doesn't constitute a valid add-on archive. For instance, I'd imagine that ZIP file support would encourage users to try to install add-ons from GitHub repo archives, etc.

By opting for a custom file format I felt that we could eliminate an entire class of potential bug reports. I mean, there must be a reason why Chrome/ium uses `.crx`, Firefox `.xpi`, and VS Code `.vsix`.

*Why "APKX" ?*

Well, I couldn't think of anything better. I guess it plays into that trope of using `x` in some way to identify extensions, as demonstrated by the file types mentioned above. However, I'm totally open to suggestions.

*Why make the `mod` manifest key optional?*

One of the use cases I envision APKX files covering is providing optional extensions to existing add-ons. These could be things like additional themes, language-specific dictionaries, etc. In cases like this you would want to copy additional files to a specific add-on directory without necessarily changing the modification date stored by Anki (as that might impede further updates from AnkiWeb).

### UI Implementation

This PR currently extends Anki's UI with the following new features:

- A new button in the add-on manager that allows users to select one or more APKX files to install
- The ability to drag and drop APKX files onto the add-on manager to quickly install them

Both of these UX flows provide ample feedback on the installation process, notifying users of any errors that might arise.

Here is a quick demo that showcases all of this in action:

screencast_20190218_073236

----

### Discussion

As this PR introduces a number of significant changes to Anki's add-on system, I thought it would be best to discuss these in as broad a forum as possible. I hope it's OK if I ping some people in the add-on dev community here. In no particular order (and sorry in advance if I left anyone out!):

@Arthur-Milchior @cayennes @eshapard @FooSoft @hssm @krassowski @lovac42 @luoliyan @ospalh @phu54321 @simgunz @sth2018 @upday7

Your feedback would be very much appreciated! Please feel to use this [sample apkx](https://glutanimate.com/files/sample_addon.apkx) if you would like to give these changes a try yourself.

### CODE REVIEW

**Comment by phu54321** [comment]
apkx looks like an android apk. Hope it had other extensions (.akpz?)

**Comment by glutanimate** [comment]
@phu54321 Thanks for the feedback! Definitely some valid points in there. Let me address each of them individually:

> apkx looks like an android apk. Hope it had other extensions (.akpz?)

That's true. There's also a point to be made that users might confuse it with Anki's deck format (.apkg). On the other hand I think the similarity to apkg helps identify it as something related to Anki. akpz isn't too bad either, but to be honest I'm not 100% sold on either. Let's see what other people have to say.

> I think using plain zip would be better for development purpose: no need to reimplement our own zip library.
> .ipa and .apk files are zip too, but nobody tries to pack them themselves. I think you're concerning too much?

Just to clarify: The files would simply be renamed ZIP files. You wouldn't need to change the library or app you use in your build scripts, just make sure to – manually or programmatically – rename the file once it's all packaged up. (That is if you're planning to distribute the add-on outside of AnkiWeb. I see no reason why AnkiWeb uploads shouldn't continue to support the current zip packages).

It's true that using plain zip files would reduce some of the effort in updating existing development tooling. However, I think the time saved through that has to be carefully weighed against potential user errors when using a common file type. I would assume that's the same reason why Anki went with apkg files for deck exports, even though they are also just zip files under the hood. (That and being able to register Anki as the default handler for these files).

This definitely is defensive programming, but I think it's worthwhile personally.

**Comment by krassowski** [comment]
I like this proposal. I just have a few (minor) questions related to beta-testing:

**Beta / development / debug versions of add-ons** 
How would that behave when instaling a new (beta) version when the user already has an older version (e.g. from AnkiWeb) installed? Is the old version going be replaced with the newer one, or just deactivated? For normal updates, the former seems more intuitive, but for the beta/dev/debug releases I would love to see the latter, so the user can easily revert to the old one or quickly switch between to investigate differences.

Also, it may be a good idea to have an icon on the list (or just text in brackets) indicating that this particular add-on entry is not a "normal" release but an unreleased (beta/dev/debug) version. This may help users discriminate between add-ons installed from AnkiWeb (so presumably stable releases) and add-on versions from GitHub which may not be stable (unless the author marks those as stable releases).

So, I would propose to add a `mode` (`str`) [optional?] field with a few encouraged values: "release", "debug", "development" (or a bunch of more specific "alpha" / "beta" / "RC"). Any value other than "release" would add a flair / text in parenthesses by the add-on name on the list.

The practice of having a development version indication is quite common, for example different icon of Firefox Niglhtly (or of a number of Android apps) or a small red indicator bar in JupyterLab dev release.

**Comment by Arthur-Milchior** [comment]
Ankiweb show a warning stating to use add-on only if you trust the author. I believe that recalling that in your addon message would be nice too. It's not necessarily clear how much power this zip file would have. (And i'm not taking into account here the fact that this waring makes absoultly no sens. There is no reason for anyone to trust any add-on developper, and can't check the code of all add-ons)

The idea seems nice, but I fail to see a case where I'll actually want to use it. If one day I decide to co-develop something with someone, having a git repo in the add-on folder seems quite easier. Since we co-develop, I assume that the other person would be able to correct their bug if required.

But if it's ok to do pull request with such big change, I'd like to implement a version which takes update from github (or any git repo) instead of ankiweb. That certainly would make some things simpler.

**Comment by zjosua** [comment]
I can totally see the use of this for deploying beta builds.

Just recently I accidentally upacked a zip of the git repo in a friends `addons21` folder, when I tried to install that wasn't released for 2.1 on AnkiWeb yet.

**Comment by lovac42** [comment]
Not a bad idea. I prefer .adze for addon zip extension or just .adz

The changes are small enough to discourage new addon developers but not enough to prevent major problems of distribution. If an apkx or adze file is missing a manifest, it should still install with a warning tag. Once imported, the manifest should be renamed or stripped to prevent repackaging and transferring the addon in case it was modified. Add checksum for file verification, but that maybe a bit much.

Some additional fields I like to see, which are pretty self explanatory: manifest_version, minimum_anki_version, icon, description, support_url, download_source

**Comment by dae** [comment]
I agree there's a need for this, think renamed zip files are the way to go, and like how the proposed implementation keeps things simple.

Re filenames: what about something more verbose like .addonpkg?

Re modes: is that really required when you could append things like (beta) to the add-on name?

Re moving between stable and beta builds: perhaps the manifest and meta.json could be expanded to include a "conflicts", which lists any packages that conflict. When the user tries to install or re-enable an add-on, if any conflicting items are found (either a->b or b->a), the user could be warned that the conflicting items will be disabled, and asked if they wish to proceed.

Arthur: zip files are a simpler solution, and they allow for offline distribution.

lovac: I don't think Glutanimate's proposing that add-on authors must create a manifest to run their own code - the package is simply a means of distribution, and thus I think it's fine to require that a manifest be present and correct in that case. I'd prefer the fields were kept to the minimum really useful ones than adding a lot of ones that may only get infrequently used. Checksums should not really be necessary as there's a crc32 in the zip already.

**Comment by ijgnd** [comment]
If you consider ".addonpkg" as the extension why not add just one character and go for ".ankiaddon"? Non-English speaking (non-technical) users will not understand the meaning of "pkg".

**Comment by Arthur-Milchior** [comment]
I'm prettty strongly in favor of conflict information.
I think taht a way to help addon creator anticipate conflict would be to
ask us to state the setof  methods are monkey patched. Indeed, one common
conlict cause beeing that two addons patch the same method.

All of my addon already contains this information in thrir readme file, and
I would clearly like to see this done in a systematic and usable way.

**Comment by dae** [comment]
addonpkg is consistent with apkg and colpkg, but ankiaddon works for me too.

**Comment by glutanimate** [comment]
Thanks for chiming in, everyone! I'm glad this proposal has been received well. And @dae, it's awesome that you're on board with this! I've been a bit strapped for time these past couple of days and still am right now, so I won't be able to address all the points raised just yet. I'm hoping to get back on that tomorrow.

For now I just wanted to mention that I took the liberty to host a [quick poll](https://docs.google.com/forms/d/1q10Fjj-1alSTo-mLC2XoivjE-AfzX-VzeuAKZSZ94Yw) on the proposed file names via Reddit and Twitter. This is what the results look like so far:

screenshot_20190221_205700

`.ankiaddon` seems to be winning by a good margin. The public vote is not the only thing to consider, of course, but personally I'd be happy to go along with it in this case. I rather like how straightforward `.ankiaddon` is.

If there aren't any further objections I would go ahead and update the extension now.

**Comment by glutanimate** [comment]
OK, back to it:

Agreed about the need for conflict resolution, both between multiple builds of the same add-on and between different add-ons. However, I think I would prefer to defer the latter and other more sophisticated uses of the manifest file until a future point in time. There are simply a lot more considerations at play if we start talking about expanding the scope of manifest files. For instance:

Would it still make sense to copy the contents of the file to meta.json? If not, which role would meta.json play going forward? If we start using manifests for AnkiWeb downloads, should fields like the add-on name take precedence over the metadata returned from AnkiWeb? Should we switch to proper JSON schema validation and versioning at some point? etc.

So at least for now I would like to keep the changes limited to those facilitating local distribution.

I've tried to stick to that with the latest two commits while also taking the discussion thus far into consideration. The changes are as follows:

- Refactored the implementation to set the stage for a broader use of the manifest file
- Added an optional `conflicts´ field to the manifest schema and implemented a series of forward/reverse conflict checks

The manifest schema now looks as follows:

* `name` (`str`) [required]: Display name of the add-on (e.g. `Review Heatmap`)
* `package` (`str`) [required]: Package name of the add-on, i.e. the subfolder within Anki's `addons21` folder the archive should be unpacked to (e.g. `review_heatmap` or `1771074083`)
* `mod` (`int`) [optional]: Modification/creation time of the package as a unix timestamp (similar to AnkiWeb and in lieu of a canonical versioning scheme)
* **`conflicts` (`list`) [optional]: A list of incompatible add-on packages (e.g. [`addon1`, `11293103922`]**)

**Comment by dae** [comment]
Thanks glutanimate!

**Pull request merged**
