### PR TITLE
integrate test suite with Travis CI

### PR DESCRIPTION
**Pull request by Inoryy**
This PR adds the config file with necessary steps to get Anki test suite running, but you'll have to manually enable the project in your Travis console to see the results.
See [here](http://docs.travis-ci.com/user/getting-started/) for more details.

Here's a [sample build](https://travis-ci.org/Inoryy/anki/builds/60231896) output. Seems to be running through full suite without issues.

### CODE REVIEW

**Comment by dae** [comment]
We don't have a pressing need for this, but I'll leave it around in case we need it in the future - thanks for taking the time to contribute.

**Comment by samrocketman** [comment]
:+1:

**Comment by RawToast** [comment]
Inoryy, I've pulled your changes into rawtoast/anki and added coveralls to the build. I would highly recommend that going forward this is added to the main build. The information provided is incredibly useful for handling pull requests, see this test request for an example:

https://github.com/RawToast/anki/pull/4

**Comment by Inoryy** [comment]
@RawToast looks fine by me, but I have no control over this PR beyond leaving it open, you should ping Damien for feedback instead since he's the one that ultimately decides what goes in.

**Comment by RawToast** [comment]
@Inoryy You're right, I should've added @dae to that message.

**Comment by dae** [comment]
Sorry, as mentioned above, this is not at the top of the todo list at the moment.

**Comment by samrocketman** [comment]
That's just silly.  It's easy to integrate IMO.  1 click configuration after you log into travis ci.  There's no reason not to have it.

**Comment by RawToast** [comment]
I agree, once you start taking commits for Anki 3 this should be top priority. It only takes a few minites to integrate with travis and coveralls. 

@Inoryy I'll probably pull the entire solution out of my branch and create a new pull request with the entire solution.

@dae I want to make improvements to the Anki codebase, but I can't find anything about this code freeze -- or the plans going forward. I've looked around the support site and forums but can't find anything concrete. This probably isn't the place for this, but what sort of changes are you thinking of implmenting going forward?

I understand from the comments here that a rewrite is not going to happen. Is there any value in making code readability changes right now?

**Comment by dae** [comment]
I'm still mulling over what the next version should look like, so I'd prefer people not try to contribute at the moment as I don't want any effort to be wasted. If you're itching to contribute, add-ons like the image occlusion add-on are popular and could do with some more attention :-)

**Comment by tbabej** [comment]
@dae Any chance of breaking the deadlock here? I guess people want to help - me included, and this   kind of stifles any development unless somebody decides to do a fork. This state has been ongoing for almost a year now? It's unfortunate since I consider Anki a superb piece of software and would love to see it move forward.

Regarding this pull request, I'm with @samrocketman - there is really no reason for not merging. This will never conflict with anything (it's only a separate .travis-ci file) and work has already been done.

**Comment by dae** [comment]
I'm sorry, I may be old fashioned here, but I don't see it as the big deal you make it out to be. The tests can easily be run directly from the command line, and being notified that you've broken something after you commit seems backward to me - you should ideally be running the tests before you commit anything, which you can even do automatically with a git precommit hook.

It's been a hectic year and I haven't made nearly as much progress on the next update as I would have liked, but it has not been abandoned, and hopefully I'll have a development branch available in a few months that people can start working on if they wish to. In the mean time, if you want to contribute to the existing code base, add-ons are an option as mentioned above.

**Comment by tbabej** [comment]
Regarding Travis integration, the advantage is that you get tests being run on every pull request automatically - hence you don't need to verify that manually. The info automatically appears on the pull request without any need for manual intervention. Also, any newcomer to the project sees that the development branch builds and passes the tests via the badge that can be added to the README, which is a good thing.

**Comment by samrocketman** [comment]
Unsubscribing, this discussion brings me no benefit.  Maintainer doesn't care and neither do I.  If you're really miffed about this discussion then just don't contribute to the project.  I'm not going to.

**Comment by dae** [comment]
@tbabej thanks for elaborating, I wasn't aware the tests would also show up in a pull request. When I open up a dev branch in the future, I'll look at integrating this.

**Comment by RawToast** [comment]
@dae You can see an example on my fork here (Coveralls is also integrated) https://github.com/RawToast/anki/pull/3

The full setup (including this pull request) is in my version of : https://github.com/dae/anki/pull/103

**Pull request merged**
