### PR TITLE
Removed magic numbers for card types and replaced with constants.

### PR DESCRIPTION
**Pull request by imipolexg**
Still needs to be done for SQL strings and other magic constants.
Think I got all the card.type instances but there might be one or two I missed.

### CODE REVIEW

**Comment by dae** [comment]
2.0 is currently in maintenance mode as we work towards a new version, so I'm not accepting patches except for important bugs at the moment. There's nothing wrong with constants per se, but they do make the sql queries a bit more cumbersome, which is why they're not used for those numbers in the scheduling code.

**Comment by imipolexg** [comment]
Fair enough. I had been doing a read through of the code to understand the scheduling algorithm and this made things more readable for me. Any info on the new version? I use Anki daily and would happily contribute.

**Comment by dae** [comment]
Thank you for the offer! We're in the early planning stages at the moment, but once things are a bit more concrete I plan to post on the beta testing section of the support site, so please subscribe to updates there.

**Comment by addonszz** [comment]
Humans can easily understand things like non-magic numbers:
```python
card.type == CARD_NEW
```
But to the computer, there is no difference. Then much better write it non-magic right away:
```
Good programmers write code that humans can understand. Martin Fowler, 2008.
```
Keep using magic number is the same as to obey every programmer look at a dictionary to decode the number, until they finally memorize it by repetition, which is ironically what is this program code about.

Putting another words, can you imagine how frustrating is to look a dictionary all the time while reading a text? The same applies to computing code. This was/is not a patch. This changes nothing on the code to the computer view. It is just like documentation for humans. Of course, if it was a bad written documentation, could broke the program or cause bugs. However, as it is a small change, it could be reviewed, if and only if, you had time available.

Or I can be just being nuts while thinking loud, so, good bye.

**Comment by dae** [comment]
I'd be happy to merge this into 2.1 if you'd still like to contribute it - could you please drop me a message on the support site confirming the license as mentioned in the LICENSE file?

**Comment by dae** [comment]
closing until we hear back from you

**Pull request closed without merging**
