### PR TITLE
Makefile improvements for flatpak

### PR DESCRIPTION
**Pull request by dsd**
These changes are useful for the efforts to distribute Anki via flatpak (https://github.com/flathub/flathub/pull/275) but should also be useful for all users/distros that use this, since they improve behaviour and consistency of the Makefile install rules.

### CODE REVIEW

**Comment by dae** [comment]
It seems mostly ok, but the designer folder is not required, the locale folder is required, and the LICENSE/README files should be installed somewhere (perhaps /usr/share/doc/anki)

**Comment by dsd** [comment]
Updated to not install designer, and install the READMEs and license.
However I can't see a locale folder to install?

**Comment by dae** [comment]
The locale folder is included in the source tarballs, and mentioned in README.development.

**Comment by dsd** [comment]
Thanks for the clarification. I've updated the pull request to install the locale dir if it is present.

**Comment by dae** [comment]
cheers

**Comment by dae** [comment]
If you submit a patch that changes install/uninstall to run separate copy and setupmime targets but keeps the current behaviour, I'll merge it.

**Pull request merged**
