### PR TITLE
Create Code of Conduct

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
ping @dae

### CODE REVIEW

**Comment by dobon** [comment]
Why? The Coding Covenant code of conduct is highly divisive among developers. The 'edit'-page wars on Wikipedia are more than enough evidence of that, but a google search will also confirm that this is a highly contentious piece of non-code that has spread discontent through repositories like a pernicious virus.

As far as I know this is not in response to any manifest problems in the community or codebase (I've reviewed both over multiple years), so I see no reason to divide our potential contributors over political lines. In any case, this contributes essentially nothing to the project but 3.31 pointless kilobytes, so I would close and not merge this PR, personally. Not that my thoughts are worth taking very seriously anyway! :o)

Maybe I'm missing something: I'd be happy to hear different opinions and am very open to changing my mind on this.

**Comment by sokolai** [comment]
Complete blunder, nothing gained, just a loss of time.

**Comment by dae** [comment]
I have no objections to the sentiment - I want Anki's community to be an inclusive place. I'm just not sure this really buys us much? As dobon has mentioned, harassment is something we thankfully have not had to deal with much, and I'm not sure adding a file into the repo would have any meaningful effect on the way people behave on the support site and third party forums.

I'm happy to listen to any reasoned arguments people may have, but please keep it constructive.

**Comment by lovac42** [comment]
> A code of conduct that isn’t (or can’t be) enforced is worse than no code of conduct at all: it sends the message that the values in the code of conduct aren’t actually important or respected in your community.
> 
> — Ada Initiative

It is too early at this stage. I don't see how you would enforce it given that most of the support site is handled by a 3rd party and maintaining/managing new users consume most of your time. Certainly close this for now and look back at it in 20 years. But we should all applaud SuriyaaKudoIsc for his efforts in being inclusive and trying to create a friendly environment.

**Comment by dae** [comment]
Closing this as there has been no activity for 2 weeks - we can revisit it in the future if needs be.

**Pull request closed without merging**
