### PR TITLE
Use litteral dict that are more efficient

### PR DESCRIPTION
**Pull request by sieben**
https://stackoverflow.com/questions/6610606/is-there-a-difference-between-using-a-dict-literal-and-a-dict-constructor

### CODE REVIEW

**Comment by julienbaley** [comment]
It looks like you committed more than you intended! :)

**Comment by sieben** [comment]
Let's say that there is a lot of literal dictionary ;-) Does this PR
interests you? I can split it up.

**Comment by julienbaley** [comment]
The commit message is incorrect: most of the diff isn't about dictionaries, but about general styling (plenty of pep8-ing), so that should go in another PR.
That being said, it's not my repo.

**Comment by dae** [comment]
Ignoring the fact that the patch does more than the description says it does, please avoid big changes like this unless there's a compelling reason for them - they risk introducing regressions, and make it more likely there'll be merge conflicts in the future. This is mentioned here: https://github.com/dae/anki/blob/master/README.contributing

And regarding the specific target of this change, literal syntax is unlikely to result in a measurable performance difference outside of particularly hot code paths, and IMHO the constructor form is more convenient in some cases.

**Pull request closed without merging**
