### PR TITLE
add some updateReqs=False in tests

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I greatly appreciate having this new options. It was not in tests, so I thought I might add well add them when no computation of req is required.

### CODE REVIEW

**Comment by dae** [comment]
In the simple note types the tests use, I doubt the difference in run time is measurable, so I'm not sure this was the most productive use of your time :-)

**Comment by Arthur-Milchior** [comment]
To be clear, I didn't only did the code of this pull request. I did plenty of changes, and only did a pull request for the small parts which may be of interest to you.

updateReqs is a nice change, I'm quite happy with it. However, it breaks the add-on 777545149 (and 802285486 I think), since both does use models.save to do something similar. So I'll probably need to remove this part of the add-ons and simply states people to update to last version of anki to have the features I did remove

**Comment by dae** [comment]
Stay tuned - there are some changes coming soon that should further improve performance with large note types.

**Comment by Arthur-Milchior** [comment]
I'm so happy to hear that. Then I guess this add-on will eventually returns. As you probably guessed, I'm indeed following the updates.

**Pull request merged**
