### PR TITLE
Log invalid model references

### PR DESCRIPTION
**Pull request by agentydragon**

### CODE REVIEW

**Comment by dae** [comment]
Anki doesn't use the logging module. There is a collection.log() method that writes messages to a log file that users can send for support, but it doesn't get used much. As 'use the check database' function is the first thing users are told to do when things go wrong, and it should cover this case already, logging in this case probably doesn't buy us much.

**Comment by agentydragon** [comment]
Actually this PR was sort of a way I wanted to test what you'd think about adding logging not tied to the `Collection` object :)
(I don't have any motivation to actually log this particular case.)

Logs in `collection.log` do, as far as I understand, log operations on the collection. But I think it's often useful to log more than just that.

* If you're reproducing a bug or developing a new feature, it's useful to add in extra debug logs (or increase debug level).
* Some operations might be useful to log even if they aren't tied to a `Collection` object - some examples that come to mind are errors when invoking `mpv` or errors in parsing a template.
* (my case) One of my ~8 installed addons will, sporadically, throw some JavaScript error. The JavaScript error printed to the console just prints 2 lines which are not enough to identify which addon did it. In this case, it would be nice if there were more logs somewhere that said e.g. "the hook that failed was named ... and installed by addon ...".

What do you think about cases like this in general - when there's something that would be useful to log, but not tied to a `Collection` object?

**Comment by dae** [comment]
I'm not sure extensive logging would buy us much at the moment. In Python, debug/trace level statements can be ignored by configuring the logging system, but you still pay the cost of the function calls as they can't be compiled out, which can be wasteful in hot paths. I tend to add a bunch of print statements when I need to debug a piece of code, and then remove them after debugging the issue. The times when I've needed to add print statements to the same parts of the code to debug a separate issue have been rare, and if they were left in as logging calls they'd just be noise.

I'm afraid adding logging probably wouldn't solve your add-on problem anyway, as if it's wrapping a function, Anki would have no way of knowing what is causing the Javascript error.

**Comment by agentydragon** [comment]
I'll poke into my addon problem a bit and see if I can find some way to make my problem produce a more understandable error...

**Pull request closed without merging**
