### PR TITLE
Clean up imports

### PR DESCRIPTION
**Pull request by solarmist**
I'm trying to help clean up the codebase to make it easier for automated tools like flake8 to keep quality high.  I will attempt to make any pull requests I do extremely specific to not introduce churn or mix concerns.

My first change is to directly and explicitly import everything (with the exception of aqt/qt.py) so that it's obvious where definitions come from an dos that mistakes of redefining imports don't occur.  I think I moved some constants to the constants file too.

I've built and run this directly on both macOS and Windows 10.

Let me know if there's anything else you'd like to see for this change.

### CODE REVIEW

**Comment by solarmist** [comment]
I've updated the .pylintrc with the pylint --generate-rcfile (so that people can see options here) and moved flags out of tools/lint.sh and into the .pylintrc file so that options aren't spread into different locations.

**Comment by dae** [comment]
I'm afraid such refactoring would likely break a bunch of add-ons, so it's not something that can be done at the moment - please see README.contributing.

**Comment by solarmist** [comment]
That's exactly the thing I'd like to help address. If people are afraid to change code then it will become fossilized and that's how software projects die.  Instead if any edge cases are clearly understood via the code it can be fixed to be more robust.

I've read the README.contributing and that's why I chose such a narrow change.  Merely making explicit all of the implicit dependencies.   

I believe the solution to that problem is to make the codebase more clear, explicit in the what is being done/why it is being done, and making the existing code more robust.  

The ways to accomplish that are by:

- Bringing the code in line with standard python development practices
- Being explicit about what is being done and why
-- For things like breaking addons then someone just needs to get a list of those add-ons and write integration tests for them so if someone else comes along with a nice contribution they are able to know wether it is possible to be merged into the codebase.
- Writing unit tests and docstrings to make functionality explicit


I'm refactoring this code in order to understand it, but I am very willing to put in some additional effort in order to make the codebase better for everyone and to make it easier for others to contribute.

Instead of closing this pull request please work with me to figure out how to enhance the stability of Anki and document the gotchas so that other people aren't guessing wether their change will be rejected because of things they don't know or can't know about.

I can think of several ways to accomplish this:

- Explicitly listing the add-ons that would break and working through the list to up date them
- Writing integration tests for a handful of popular add-ons that are known to do non-standard things (like transitively depending on modules being available).
- Marking certain files as legacy and updating the majority of the file, but leaving a couple of special files like qt.py and starting to document the ways in which breaks could occur and squashing those one by one.
- Less desirable would be to start and Anki 2.2 branch where these more extreme changes can live

**Comment by dae** [comment]
It's great that you want to improve Anki, and the codebase is certainly overdue for a cleanup. I'm afraid our definitions of 'narrow change' differ however - this patch changes many hundreds of lines, and I can be reasonably confident that it will break things. I don't think such changes should be done in the middle of a stable release cycle, as the primary goal at the moment is whittling down the outstanding bugs. Making things easier for developers is a great goal, but it shouldn't come at the expense of the end user.

Once the dust has settled on 2.1 and the majority of 2.0 users have moved over, there will be time to start thinking about more major changes in a new development branch. For now, I'm afraid such changes will need to wait.

**Pull request closed without merging**
