### PR TITLE
Use fbs to deploy Anki

### PR DESCRIPTION
**Pull request by mherrmann**
[fbs](https://github.com/mherrmann/fbs) is a build system for deploying PyQt5 apps. It is based on PyInstaller, but takes away the many pains still associated with cross-platform desktop apps based on PyQt5:

 * Packaging missing DLLs and .so files so the frozen app runs on all users' systems
 * Creating installers
 * Code signing
 * Automatic updates

At the moment, I believe the main benefit Anki could get from using fbs are native packages for Linux. I'm not familiar with Anki's history, and it seems there were eg. `.deb` files at some point. But the home page currently only offers a `.tar.bz2` file. One of the limitations of this approach is that Anki does not have support for automatic updates. Another is that the lack of integration into the native package manager makes it impossible for users to manage Anki's installation (eg. uninstall it) in a "standard" way.

This PR is actually not yet implemented, because I wanted to gauge your interest before spending a significant amount of time on it. But, if you are open to using fbs provided my changes are "clean", I could complete the PR and add the following "features":

 * Native Anki packages for Ubuntu (`.deb`), Arch (`.pkg.tar.xz`) and Fedora/CentOS (`.rpm`).
 * Support for automatic updates on the above distributions: Publish a new version of Anki with a single command, and have your users receive it automatically via their native package manager.

To get a quick feel of what the solution will look like, please see [this article](https://build-system.fman.io/linux-gui-programming). 

In the future (or alternatively, if you wish), I can also do the same for Windows and Mac. fbs already supports these platforms, with the current limitation that code signing and automatic updates are not yet implemented. But freezing and uploading work.

For a more general introduction to fbs, please see its [tutorial](https://github.com/mherrmann/fbs-tutorial), or the [home page](https://build-system.fman.io).

### CODE REVIEW

**Comment by dae** [comment]
Thank you for the offer! I had a look over fbs's docs, and I'm afraid it doesn't look like a great fit for Anki. Aside from not wanting to host the packages on a third party server, Anki relies heavily on WebEngine, which Qt make breaking changes to in almost every major update - this is why Anki has moved away from source-based packages on Linux in favour of binary packages that continue to work when distros decide to upgrade Qt.

**Comment by dae** [comment]
Thank you for clarifying, "The hosting of your binaries is free for now. If you need certain assurances with regards to hosting, please get in touch." in the docs lead me to think otherwise.

If Anki didn't have an existing packaging solution then fbs might be appealing, but I'm afraid at this point Anki's homegrown packaging has already had considerable testing, and I'm reluctant to switch to a new solution which may introduce regressions. I do look forward to seeing how fbs progresses in the future however :-)

**Comment by mherrmann** [comment]
Thank you for pointing this out - I'll change the text you mentioned to make it clear that one can also self host.

And as a fellow engineer, I understand your decision. fbs has also had considerable testing in the wild via my [file manager fman](https://fman.io). Maybe you'll find it useful for a future project :-)

**Comment by mherrmann** [comment]
(fbs I mean. Of course you can also check out fman.)

**Pull request closed without merging**
