### PR TITLE
Idea: named queues and card typess

### PR DESCRIPTION
**Pull request by agentydragon**
Hi Damien. I think this refactor would make the scheduler code much more readable, but I didn't yet get this ready to merge, because I'm not sure how you'd feel about it - given that you currently prefer stabilizing the codebase.

WDYT?

### CODE REVIEW

**Comment by dae** [comment]
My main concern is introducing a regression due to accidentally using the wrong constant. Perhaps the best way to approach this would be to start with just the CARD_TYPE changes, and use f strings like f"... type = {CARD_TYPE_...}" so the change is easier to review. 

This would just be a stop gap however - in the long run I want to move all the sql out of the scheduler, as this code would be much easier to work with if it were just operating on card objects with enums for type and queue.

**Comment by agentydragon** [comment]
OK, doing it slowly (e.g. constant by constant) sounds good.

**Comment by agentydragon** [comment]
First part here: https://github.com/dae/anki/pull/402

Regarding the moving of SQL out of scheduler: I guess there would have to be a few glue functions between the collection and the scheduler, such as "get cards from this queue", "get first N cards from these queues according to this order", etc.

**Comment by dae** [comment]
Yep, but I think it would be a net win.

**Pull request closed without merging**
